---
title: "Plant Status"
author: "Kevin Mori"
date: "2/22/2020"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(googlesheets4)
library(tidyverse)
library(lubridate)
library(gridExtra)
library(zoo)
library(googledrive)


```

## Data collection

```{r include=FALSE, echo = FALSE}

if(sheets_has_token()==FALSE){
  sheets_auth(email = "tsutomu45@gmail.com")  
}


ss_id1 <- "1vumpWAOqvLWp6H22BnA8kpKXk-gytFkco2v2_MeZTUI"
ss_id2 <- "10NIg7C5aH61vva2kCcGt0Hek9wq2oa7c7kArHrHwKxE"
sensor_data <- data.frame(read_sheet(ss = ss_id2)[,1:4])
sensor_data <- filter(sensor_data, Device != "Portable Switch Cord 1")
sensor_data$Event.Value <- as.numeric(sensor_data$Event.Value)

colnames(sensor_data) <- c(
  "obs_dt", "device", "event", "value")
str(sensor_data)
#sensor_data$obs_dt <- floor_date(sensor_data$obs_dt, unit = "minutes")

seedling_data <- filter(sensor_data, device == "seedlingsensor") %>%
  select(-device) %>%
  filter(event != "activity") %>%
  pivot_wider(names_from = event, id_cols = obs_dt, values_from = value) %>%
  mutate(illuminance = ifelse(illuminance < 90, 0, 1)) %>%
  na.locf()

  drive_auth(email = "tsutomu45@gmail.com")
  drive_download("weather2.csv", path = "weather.csv", overwrite = TRUE)
  
  weather_data <- read.csv("weather.csv", header=FALSE, stringsAsFactors=FALSE)
  
  colnames(weather_data) <- c("timestamp","sunrise_time", "sunset_time", "condition_type",
  "current_temp", "min_temp", "max_temp", "humidity_pct", "cloud_cover_pct")
  
  weather_data$timestamp <- as.POSIXct(weather_data$timestamp, origin="1970-01-01")
  weather_data$sunrise_time <- as.POSIXct(weather_data$sunrise_time, origin="1970-01-01")
  weather_data$sunset_time <- as.POSIXct(weather_data$sunset_time, origin="1970-01-01")
  weather_data$date <- as.Date(weather_data$timestamp)
  
  

```

## Including Plots

Plots

```{r echo = FALSE}

ggplot(seedling_data, aes(x=obs_dt, y=temperature, col = factor(illuminance))) +
  geom_point() + 
  scale_color_manual(values = c("black","gold2")) +
  geom_smooth(method = "lm", fill="gray92", aes(group = factor(illuminance), col = factor(illuminance))) +
  geom_hline(yintercept = 65, col = "blue", linetype = "dashed") +
  geom_hline(yintercept = 80, col = "red", linetype = "dashed") +
  ggtitle("Germination Area 1 Temps (Light On/Off)") +
  ylab("temp (deg. f)") +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color="gray", size = 0.2),
        legend.position = "none",
        axis.title.x=element_blank(),
        axis.title.y=element_text(colour = "gray"),
        axis.text.x = element_text(colour = "gray"),
        axis.text.y = element_text(colour = "gray"))



outdoor_data <- filter(sensor_data, device == "plantsensor") %>%
  select(-device) %>%
  filter(event != "activity") %>%
  pivot_wider(names_from = event, id_cols = obs_dt, values_from = value) %>%
  mutate(humidity = humidity/100) %>%
  na.locf()


temp1 <- ggplot(outdoor_data, aes(x = obs_dt)) +
  geom_line(size = 1, aes(y = temperature, col=temperature)) +
  ggtitle("Sensor Temperature and Soil Moisture") +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color="gray", size = 0.2),
        legend.position = "none",
        axis.title.x=element_blank(),
        axis.title.y=element_text(colour = "gray"),
        axis.text.x = element_text(colour = "gray"),
        axis.text.y = element_text(colour = "gray"))

temp2 <- ggplot(outdoor_data, aes(x = obs_dt, y = humidity)) +
  geom_point(size = 1, color = "gray") +
  geom_smooth(span=0.2) +
  ylab("Soil Moisture %") +
  theme(panel.background = element_rect(fill = "white"),
        panel.grid.major = element_line(color="gray", size = 0.2),
        legend.position = "none",
        axis.title.x=element_blank(),
        axis.title.y=element_text(colour = "gray"),
        axis.text.x = element_text(colour = "gray"),
        axis.text.y = element_text(colour = "gray"))

grid.arrange(temp1, temp2)


  ggplot(data = weather_data, aes(y=humidity_pct/100, x = timestamp)) +
    geom_point(color = "gray", size = 1) +
    theme(panel.background = element_rect(fill = "white"),
          panel.grid.major = element_line(color="gray", size = 0.5)
    )+
    stat_smooth(span=0.1) +
    ggtitle("Relative Humidity Percent")
  
  ggplot(data = weather_data, aes(y=cloud_cover_pct/100, x = timestamp)) +
    geom_point(color = "gray", size = 1) +
    theme(panel.background = element_rect(fill = "white"),
          panel.grid.major = element_line(color="gray", size = 0.5)
    )+
    ggtitle("Cloud Cover Percent") +
    stat_smooth(span=0.5)

```
